Repository wecode-bootcamp-korea/35-2nd-WnB-frontend, pull requests merged in 2022-08, with the labels that each got.

#2 [35기 류승연] Card Component 구현
  package-lock.json
  package.json
  public/data/RoomData.json
  public/images/ethiopia2.jpg
  public/images/next.png
  public/images/prev.png
  public/index.html
  src/Router.js
  src/components/CardSlide.js
  src/components/ItemCard.js
  src/styles/GlobalStyle.js
Labels: 완료

#5 [35기 류승연] 메인에 카드 컴포넌트 추가로 기본 레이아웃 구현
  src/pages/Main/Main.js
Labels: 완료

#1 [35기 정억화]상세페이지
  package-lock.json
  package.json
  public/data/detailMockData.json
  public/data/detailMockData2.json
  public/images/icons/arrowicon.png
  public/images/icons/home.png
  src/Router.js
  src/components/Footer/Footer.js
  src/components/GoogleMapApi/GoogleMapApi.js
  src/components/Modal/Modal.js
  src/pages/Detail/Detail.js
  src/pages/Detail/components/DetailMainLeft.js
  src/pages/Detail/components/DetailMainRight.js
  src/pages/Detail/components/DetailMainRightBooking.js
  src/pages/Detail/components/DetailMap.js
  src/pages/Detail/components/DetailNotice.js
  src/pages/Detail/components/DetailPhoto.js
  src/pages/Detail/components/DetailTop.js
  src/styles/theme.js
Labels: 완료

#6 [35기 류승연] 목록 레이아웃 구현
  public/images/filter.png
  src/Router.js
  src/components/Card/CardSlide.js
  src/components/Card/ItemCard.js
  src/pages/List/List.js
Labels: 완료

#3 [35기 최원익] Nav 기본 레이아웃 구현 완료
  package-lock.json
  package.json
  public/images/airbnbLogo.png
  public/images/easy.jpeg
  public/images/euro.webp
  public/index.html
  src/components/Nav/BeforeSearch.js
  src/components/Nav/Nav.js
  src/components/Nav/OnClickSearch.js
  src/components/Nav/Search.js
  src/components/Nav/modal/Calender.js
  src/components/Nav/modal/GuestType.js
  src/components/Nav/modal/Location.js
  src/components/Nav/modal/ProfileContainer.js
  src/hooks/useOutsideClick.js
  src/styles/animation.js
Labels: 멘토 리뷰 요청

#9 [35기 류승연] filter button 컴포넌트화
  src/Router.js
  src/pages/List/FilterButton.js
  src/pages/List/List.js
  src/pages/ResList/ResList.js
  src/pages/ResList/ResTab.js
Labels: 완료

#7 [35기 류승연] 메인 카테고리 추가
  public/data/mainMockData.json
  public/images/favicon.ico
  src/components/Card/ItemCard.js
  src/pages/Main/Main.js
  src/pages/Main/MainCategory.js
Labels: 멘토 리뷰 요청

#10 [35기 정억화] 리스트 페이지 맵추가
  .gitignore
  package-lock.json
  package.json
  public/data/listMapData.json
  public/images/marker_black.png
  public/images/marker_white.png
  src/components/Config/Config.js
  src/components/Footer/Footer.js
  src/components/GoogleMapApi/GoogleMapApi.js
  src/components/Modal/Modal.js
  src/pages/Detail/Detail.js
  src/pages/Detail/components/Calender.js
  src/pages/Detail/components/DetailMainRight.js
  src/pages/Detail/components/DetailMainRightBooking.js
  src/pages/Detail/components/DetailMap.js
  src/pages/Detail/components/ModalWrap.js
  src/pages/List/List.js
Labels: 완료

#12 [35기 최원익]로그인 및 회원가입 모달창 생성
  src/components/Nav/BeforeSearch.js
  src/components/Nav/Nav.js
  src/components/Nav/OnClickSearch.js
  src/components/Nav/Search.js
  src/components/Nav/modal/Calender.js
  src/components/Nav/modal/ProfileContainer.js
  src/components/Nav/modal/ProfileLoginContainer.js
Labels: 완료

#11 [35기 최원익]Filter 모달창 기본설정 완료
  package-lock.json
  package.json
  public/data/FilterData.json
  public/index.html
  src/components/FilterModal/FilterModal.js
  src/components/FilterModal/component/AirbnbSlider.js
  src/components/FilterModal/component/BathRoom.js
  src/components/FilterModal/component/Bed.js
  src/components/FilterModal/component/BedRoom.js
  src/hooks/useLockBodyScroll.js
Labels: 완료

#13 [35기 정억화] 상세페이지 , 달력, 예약 통신
  .env
  package-lock.json
  package.json
  public/data/detailMockData2.json
  src/Router.js
  src/components/Modal/Modal.js
  src/pages/Detail/Detail.js
  src/pages/Detail/components/Calender.js
  src/pages/Detail/components/DetailMainLeft.js
  src/pages/Detail/components/DetailMainRight.js
  src/pages/Detail/components/DetailMainRightBooking.js
Labels: 수정 요청

#14 [35기 류승연] 예약내역 구현
  public/data/reservationData.json
  public/data/reservationListData.json
  src/Router.js
  src/components/Card/ItemCard.js
  src/components/Nav/BeforeSearch.js
  src/components/Nav/OnClickSearch.js
  src/pages/ResDetail/ResDetail.js
  src/pages/ResList/ResList.js
  src/pages/ResList/ResTab.js
Labels: 멘토 리뷰 요청

#8 [35기 정예빈] 회원가입 기능구현
  src/Router.js
  src/components/Modal/SignModal.js
  src/components/ModalBack.js
  src/components/Nav/BeforeSearch.js
  src/components/Nav/Nav.js
  src/components/Nav/OnClickSearch.js
  src/components/Nav/modal/ProfileContainer.js
  src/pages/Signup/Signup.js
  src/pages/Signup/UserInfo.js
Labels: 멘토 리뷰 요청

#4 [35기 정예빈] kakao Login 기능구현
  .gitignore
  package-lock.json
  package.json
  src/Router.js
  src/components/Modal/LoginModal.js
  src/components/Nav/Nav.js
  src/components/Nav/modal/ProfileContainer.js
  src/pages/Login/KakaoLogin.js
  src/pages/Login/Login.js
Labels: 완료
